Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,10 +1,10 @@
 pipeline {
     agent {
-    docker {
-      image 'abhishekf5/maven-abhishek-docker-agent:v1'
-      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
+        docker {
+            image 'abhishekf5/maven-abhishek-docker-agent:v1'
+            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
+        }
     }
-  }
     environment {
         DOCKERHUB_CREDENTIALS = credentials('Docker_id')
         DOCKER_IMAGE = "manoj3003/pipelie-cicd:${BUILD_NUMBER}"
@@ -25,7 +25,7 @@ pipeline {
                 sh "docker build -t ${DOCKER_IMAGE} ."
             }
         }
-        
+
         stage('Login') {
             steps {
                 withCredentials([usernamePassword(credentialsId: 'Docker_id', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
@@ -33,7 +33,7 @@ pipeline {
                 }
             }
         }
-        
+
         stage('Static Code Analysis') {
             environment {
                 SONAR_URL = "http://65.1.107.97:9000"
@@ -45,7 +45,6 @@ pipeline {
             }
         }
 
-
         stage('Push') {
             steps {
                 script {
@@ -54,12 +53,13 @@ pipeline {
                 }
             }
         }
+
         stage('Cleanup Old Docker Images') {
             steps {
                 script {
                     // Connect to EC2 and run cleanup commands
                     sh '''
-                        # List all Docker images with their IDs and tags
+                        # List all Docker images with their IDs
                         docker images -q > all_images.txt
 
                         # Get the image ID of the current Docker image
@@ -68,8 +68,18 @@ pipeline {
                         # Loop through all images and delete those that are not the current one
                         while read -r IMAGE_ID; do
                             if [ "$IMAGE_ID" != "$CURRENT_IMAGE_ID" ]; then
+                                # List containers using the image
+                                CONTAINERS=$(docker ps -a -q --filter "ancestor=$IMAGE_ID")
+
+                                if [ -n "$CONTAINERS" ]; then
+                                    echo "Stopping and removing containers using image with ID: $IMAGE_ID"
+                                    # Stop and remove containers using the image
+                                    docker stop $CONTAINERS
+                                    docker rm $CONTAINERS
+                                fi
+
                                 echo "Removing old image with ID: $IMAGE_ID"
-                                docker rmi -f $IMAGE_ID
+                                docker rmi -f $IMAGE_ID || echo "Failed to remove image $IMAGE_ID - might be in use or other error."
                             fi
                         done < all_images.txt
 
@@ -117,6 +127,7 @@ pipeline {
             }
         }
     }
+    
     post {
         always {
             emailext (
@@ -126,8 +137,8 @@ pipeline {
                               <p>Build Status: ${BUILD_STATUS}</p>
                               <p>Build Number: ${BUILD_NUMBER}</p>
                               <p>Check the <a href="${BUILD_URL}">console output</a>.</p>
-                            <body>
-                        <html>''',
+                           </body>
+                        </html>''',
                 to: 'manojvarmapotthutri@gmail.com',
                 from: 'jenkins@example.com',
                 replyTo: 'jenkins@example.com',
