Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,10 +1,6 @@
 pipeline {
-    agent {
-    docker {
-      image 'abhishekf5/maven-abhishek-docker-agent:v1'
-      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
-    }
-  }
+    agent any
+
     environment {
         DOCKERHUB_CREDENTIALS = credentials('Docker_id')
         DOCKER_IMAGE = "manoj3003/pipelie-cicd:${BUILD_NUMBER}"
@@ -67,9 +63,16 @@ pipeline {
                         # List all Docker image IDs
                         docker images -q | while read -r IMAGE_ID; do
                             if [ "$IMAGE_ID" != "$CURRENT_IMAGE_ID" ]; then
-                                echo "Removing old image with ID: $IMAGE_ID"
-                                # Try to remove the image
-                                docker rmi -f $IMAGE_ID || echo "Failed to remove image $IMAGE_ID - might be in use or other error."
+                                # List containers using the image
+                                CONTAINERS=$(docker ps -a -q --filter "ancestor=$IMAGE_ID")
+
+                                if [ -n "$CONTAINERS" ]; then
+                                    echo "Skipping removal of image $IMAGE_ID as it is being used by running containers."
+                                else
+                                    echo "Removing old image with ID: $IMAGE_ID"
+                                    # Try to remove the image
+                                    docker rmi -f $IMAGE_ID || echo "Failed to remove image $IMAGE_ID - might be in use or other error."
+                                fi
                             fi
                         done
                     '''
